---
title: "Shared Gene Network"
author: "Gerry Tonkin-Hill"
date: "`r Sys.Date()`"
output: 
  html_document:
    fig_width: 12
    fig_height: 8
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.width=20, fig.height=12,
                      echo=TRUE, warning=FALSE, message=FALSE,
                      tidy=TRUE)
options(stringsAsFactors = FALSE)
```

```{r}
library(data.table)
library(tidyverse)
library(igraph)
library(ggraph)
library(ape)
```

Load data

```{r}
Efaecalis_pa <- fread("./E_faecalis_panaroo/gene_presence_absence.Rtab.gz", data.table = FALSE) %>% as_tibble()
Efaecalis_pa_matrix <- data.matrix(Efaecalis_pa[,2:ncol(Efaecalis_pa)])
rownames(Efaecalis_pa_matrix) <- Efaecalis_pa$Gene
Efaecalis_meta <- fread("./E_faecalis_panaroo/metadata_E_faecalis.csv.gz", data.table = FALSE) %>% as_tibble()

Efcm_pa <- fread("./Efcm_panaroo/gene_presence_absence.Rtab.gz", data.table = FALSE)
Efcm_pa_matrix <- data.matrix(Efcm_pa[,2:ncol(Efcm_pa)])
rownames(Efcm_pa_matrix) <- Efcm_pa$Gene
Efcm_meta <- fread("./Efcm_panaroo/metadata_Efcm.csv.gz", data.table = FALSE)
```

Generate within species gene composition distance matrices

```{r}
pairwise_sim <- function(pa){
  d <- matrix(rep(colSums(pa), ncol(pa)), 
       nrow=ncol(pa), ncol = ncol(pa))
  d <- (2*crossprod(pa))/(d + t(d))
  return(d)
}

Efaecalis_sim <-pairwise_sim(Efaecalis_pa_matrix)
Efcm_sim <- pairwise_sim(Efcm_pa_matrix)
```

convert to a network given an edge cutoff and add metadata

```{r}
sum(Efaecalis_sim<0.90)/ncol(Efaecalis_sim)^2

sparse_Efaecalis_sim <- Efaecalis_sim
sparse_Efaecalis_sim[sparse_Efaecalis_sim<0.9] <- 0
diag(sparse_Efaecalis_sim) <- 0

g <- graph.adjacency(sparse_Efaecalis_sim, weighted = TRUE)
edges <- cbind(igraph::get.edgelist(g), igraph::get.edge.attribute(g)$weight)

fwrite(edges, file = "Efaecalis_edges.csv.gz", sep=",", quote = FALSE)
```

```{r}
sum(Efcm_sim<0.9)/ncol(Efcm_sim)^2

sparse_Efcm_sim <- Efcm_sim
sparse_Efcm_sim[sparse_Efcm_sim<0.9] <- 0
diag(sparse_Efcm_sim) <- 0

g <- graph.adjacency(sparse_Efcm_sim, weighted = TRUE)
edges <- cbind(igraph::get.edgelist(g), igraph::get.edge.attribute(g)$weight)

fwrite(edges, file = "Efcm_edges.csv.gz", sep=",", quote = FALSE)
```

##Additional analyses

Additional analysis to respond to reviewers comments.

Association analysis between gene presence absence and hospitilisation isolates

```{r}
keep <- Efaecalis_meta$ID2[Efaecalis_meta$Source %in% c("Non-hospitalized person", "Hospitalized patient")]
keepID1 <- Efaecalis_meta$ID[Efaecalis_meta$Source %in% c("Non-hospitalized person", "Hospitalized patient")]
Efaecalis_pa_df <- as_tibble(Efaecalis_pa_matrix[, colnames(Efaecalis_pa_matrix) %in% keep]) %>% 
  add_column(Gene=rownames(Efaecalis_pa_matrix), .before = 1)
category <- Efaecalis_meta$Source[match(colnames(Efaecalis_pa_df)[2:ncol(Efaecalis_pa_df)], Efaecalis_meta$ID2)]
colnames(Efaecalis_pa_df) <- gsub('.velvet','', colnames(Efaecalis_pa_df))
names(category) <- colnames(Efaecalis_pa_df)[2:ncol(Efaecalis_pa_df)]

raxml_tree <- ape::read.tree("./RAxML_bestTree.ml_E07132_raxml")
raxml_tree <- drop.tip(raxml_tree, tip = raxml_tree$tip.label[!raxml_tree$tip.label %in% keepID1])

d <- ape::cophenetic.phylo(raxml_tree)
colnames(d) <- rownames(d) <- gsub('_1$', '', colnames(d))
index <- match(colnames(Efaecalis_pa_df)[2:ncol(Efaecalis_pa_df)], colnames(d))
d <- d[index, index]

stopifnot(all(colnames(index)==colnames(Efaecalis_pa_df)[2:ncol(Efaecalis_pa_df)]))
stopifnot(all(names(category)==colnames(Efaecalis_pa_df)[2:ncol(Efaecalis_pa_df)]))

mds <- as_tibble(cmdscale(d, k = 10)) %>% add_column(category=category)

ngenes <- ncol(Efaecalis_pa_df)-1
test <- (rowSums(Efaecalis_pa_df[,2:ncol(Efaecalis_pa_df)])> 0.05*ngenes) & (rowSums(Efaecalis_pa_df[,2:ncol(Efaecalis_pa_df)]) < 0.95*ngenes)
sum(test)
results <- map_dfr(Efaecalis_pa_df$Gene[test], ~{
  df <- mds
  df$gene_pa <- unlist(Efaecalis_pa_df[Efaecalis_pa_df$Gene==.x, 2:ncol(Efaecalis_pa_df)])
  if ((3 > sum(df$gene_pa)) | (0.95*nrow(df) < sum(df$gene_pa))) return(tibble())
  res <- broom::tidy(glm(factor(category) ~ gene_pa + V1 + V2 + V3 + V4 + V5 + V6 + V7 + V8 + V9 + V10, data = df, family = 'binomial'))
  res <- res %>%
    filter(term=='gene_pa') %>%
    add_column(gene=.x, .before=1) %>%
    add_column(n_hospital=sum(df$gene_pa & df$category=="Hospitalized patient")) %>%
    add_column(n_nonhospital=sum(df$gene_pa & df$category=="Non-hospitalized person"))
  return(res)
}) %>% arrange(p.value)

results$adj.p.value <- p.adjust(results$p.value, method='bonferroni')
results$hospital_prevalence <- results$n_hospital/sum(category=='Hospitalized patient')
results$nonhospital_prevalence <- results$n_nonhospital/sum(category=='Non-hospitalized person')
sig_results <- results %>% filter(adj.p.value<0.05)

fwrite(sig_results, 'hospital_vs_nonhospital_pa_analysis.csv', sep=',')
table(sig_results$estimate<0)
data.table(sig_results)
```

Generate a Venn diagram

```{r}
library(VennDiagram)
 
# Generate 3 sets of 200 words
set1 <- Efaecalis_pa_df$Gene[rowSums(Efaecalis_pa_df[,c(FALSE, category=='Hospitalized patient')])>0] 
set2 <- Efaecalis_pa_df$Gene[rowSums(Efaecalis_pa_df[,c(FALSE, category=='Non-hospitalized person')])>0] 

# Prepare a palette of 3 colors with R colorbrewer:
library(RColorBrewer)
myCol <- brewer.pal(3, "Pastel2")[1:2]

# Chart
venn.diagram(
        x = list(set1, set2),
        category.names = c("Hospitalized patient" , "Non-hospitalized person " ),
        filename = 'venn_hospitalised_vs_not.png',
        output=TRUE,
        
        # Output features
        # imagetype="png" ,
        height = 700 , 
        width = 1200 , 
        resolution = 300,
        compression = "lzw",
        
        # Circles
        lwd = 2,
        lty = 'blank',
        fill = myCol,
        
        # Numbers
        cex = .6,
        fontface = "bold",
        fontfamily = "sans",
        
        # Set names
        cat.cex = 0.6,
        cat.fontface = "bold",
        cat.default.pos = "outer",
        cat.pos = c(-27, 27),
        cat.dist = c(0.055, 0.055)
)
```


